"use client";

/**
 * Exam audio controller — a single persistent (detached) <audio> element that
 * survives the whole exam session.
 *
 * Why: Safari/WebKit grants autoplay permission PER ELEMENT. The old flow
 * mounted a fresh <audio> per question and called play() from setTimeout
 * chains (outside any user-gesture stack), so on iOS Safari / WeChat / QQ
 * browser every question after the first was blocked (NotAllowedError) and
 * the exam went silent. The fix: unlock ONE element with a silent WAV inside
 * the real "start exam" click, then reuse that same element for every clip —
 * an already-unlocked element may be play()ed programmatically on iOS.
 *
 * Framework-free (pure JS class-like factory) so it can be unit-tested
 * without React and shared by the listening + speaking exam shells.
 */

// ~60ms of 8kHz 16-bit mono silence (all-zero PCM), generated by a throwaway
// node script (RIFF/WAVE header + zero-filled data chunk, base64). Used only
// to complete the per-element autoplay unlock inside the start-exam gesture.
const SILENT_WAV =
  "data:audio/wav;base64,UklGRuQDAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACABAAZGF0YcADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

// Watchdog timings. After play() we expect a 'playing' event; if it never
// arrives the user hears nothing and nothing on screen says why. 4s covers a
// slow-but-working start; while the element reports NETWORK_LOADING we extend
// to a 15s total budget (buffering, not blocked) before declaring failure.
const WATCHDOG_INITIAL_MS = 4000;
const WATCHDOG_TOTAL_MS = 15000;

/**
 * Create an exam audio controller. SSR-safe: on the server returns an inert
 * stub with the same surface so accidental server calls are no-ops.
 */
export function createExamAudioController({ onTelemetry } = {}) {
  if (typeof window === "undefined" || typeof document === "undefined") {
    const noop = () => {};
    return {
      unlock: noop, play: noop, preload: noop, retry: noop, stop: noop,
      destroy: noop, subscribe: () => noop,
      getState: () => "idle", getCurrentSrc: () => null, isUnlocked: () => false,
    };
  }

  // Detached element — never mounted into the DOM (detached audio still
  // plays), never recreated, so the WebKit per-element unlock survives the
  // whole exam including React remounts of the question components.
  const el = document.createElement("audio");
  el.preload = "auto";

  let state = "idle"; // idle | unlocking | loading | playing | ended | blocked | error
  let unlocked = false;
  let currentSrc = null;
  let currentMeta = null;
  let preloadedSrc = null;
  let lastPlay = null; // { src, meta } — for retry()
  let playCalledAt = 0; // Date.now() at play() — for firstFrameMs
  let watchdogTimer = null;
  let watchdogStartedAt = 0;
  let expectingSourceChange = false; // our own pause/src swap → not an interruption
  let interrupted = false; // paused while page hidden (tab switch / phone call)
  // Debug counter: AbortError is the one error we deliberately swallow (a src
  // swap / pause racing an unresolved play() promise), but we still count it.
  let abortErrorCount = 0;

  const listeners = new Set();

  function emit(event) {
    // Snapshot so a listener unsubscribing mid-loop doesn't skip others.
    for (const fn of Array.from(listeners)) {
      try { fn(event); } catch { /* listener errors must not break playback */ }
    }
    if (onTelemetry) {
      try { onTelemetry(event); } catch { /* telemetry must never throw */ }
    }
  }

  function clearWatchdog() {
    if (watchdogTimer) { clearTimeout(watchdogTimer); watchdogTimer = null; }
  }

  // Arm/extend the silence watchdog. If 'playing' hasn't fired when it goes
  // off: still fetching (NETWORK_LOADING) → report buffering and extend up to
  // the total budget; otherwise (or budget spent) → blocked(silent-timeout).
  function armWatchdog(delayMs) {
    clearWatchdog();
    watchdogTimer = setTimeout(() => {
      watchdogTimer = null;
      if (state === "playing") return;
      const elapsed = Date.now() - watchdogStartedAt;
      if (el.networkState === 2 /* NETWORK_LOADING */ && elapsed < WATCHDOG_TOTAL_MS) {
        emit({ type: "buffering", src: currentSrc, meta: currentMeta });
        armWatchdog(Math.min(WATCHDOG_TOTAL_MS - elapsed, WATCHDOG_TOTAL_MS));
        return;
      }
      state = "blocked";
      emit({ type: "blocked", reason: "silent-timeout", src: currentSrc, meta: currentMeta });
    }, delayMs);
  }

  // ── element event wiring (bound once for the controller's lifetime) ──

  function onPlaying() {
    clearWatchdog();
    interrupted = false;
    state = "playing";
    emit({
      type: "playing",
      src: currentSrc,
      meta: currentMeta,
      firstFrameMs: playCalledAt ? Date.now() - playCalledAt : null,
    });
  }

  function onEnded() {
    clearWatchdog();
    state = "ended";
    emit({ type: "ended", src: currentSrc, meta: currentMeta });
  }

  function onError() {
    // Ignore errors for the empty src set by destroy()/stop() teardown.
    if (!currentSrc) return;
    clearWatchdog();
    state = "error";
    emit({
      type: "error",
      errorName: "MediaError",
      mediaErrorCode: el.error ? el.error.code : null,
      readyState: el.readyState,
      networkState: el.networkState,
      src: currentSrc,
      meta: currentMeta,
    });
  }

  function onWaiting() {
    if (state !== "playing" && state !== "loading") return;
    emit({ type: "buffering", src: currentSrc, meta: currentMeta });
  }

  function onTimeUpdate() {
    emit({
      type: "progress",
      currentTime: el.currentTime,
      duration: el.duration,
      src: currentSrc,
      meta: currentMeta,
    });
  }

  function onPause() {
    // A pause we didn't cause, before 'ended', while the page is hidden =
    // the OS/browser cut us off (tab switch, phone call, screen lock).
    if (expectingSourceChange || state === "ended") return;
    if (document.visibilityState === "hidden") interrupted = true;
  }

  function onVisibilityChange() {
    if (document.visibilityState !== "visible") return;
    if (interrupted && state !== "ended") {
      interrupted = false;
      state = "blocked";
      emit({ type: "blocked", reason: "interrupted", src: currentSrc, meta: currentMeta });
    }
  }

  el.addEventListener("playing", onPlaying);
  el.addEventListener("ended", onEnded);
  el.addEventListener("error", onError);
  el.addEventListener("waiting", onWaiting);
  el.addEventListener("stalled", onWaiting);
  el.addEventListener("timeupdate", onTimeUpdate);
  el.addEventListener("pause", onPause);
  document.addEventListener("visibilitychange", onVisibilityChange);

  // ── public API ──

  /**
   * Unlock the element. MUST be called synchronously inside a user gesture
   * (the start-exam click). Idempotent. Also pre-unlocks speechSynthesis so
   * the TTS fallback can speak later without its own gesture.
   */
  function unlock() {
    if (unlocked) return;
    state = "unlocking";
    try {
      el.src = SILENT_WAV;
      const p = el.play();
      if (p && typeof p.then === "function") {
        p.then(() => {
          unlocked = true;
          if (state === "unlocking") state = "idle";
          emit({ type: "unlocked" });
        }).catch((err) => {
          if (err && err.name === "AbortError") { abortErrorCount++; return; }
          state = "idle";
          emit({ type: "unlock-blocked", errorName: err && err.name });
        });
      } else {
        // Very old engines return undefined from play() — assume it worked.
        unlocked = true;
        state = "idle";
        emit({ type: "unlocked" });
      }
    } catch (err) {
      state = "idle";
      emit({ type: "unlock-blocked", errorName: err && err.name });
    }
    // Pre-unlock iOS speechSynthesis for the TTS fallback: a near-empty
    // utterance spoken inside the gesture, cancelled immediately.
    try {
      if (typeof speechSynthesis !== "undefined" && typeof SpeechSynthesisUtterance !== "undefined") {
        speechSynthesis.speak(new SpeechSynthesisUtterance(" "));
        speechSynthesis.cancel();
      }
    } catch { /* feature-detect only; TTS unlock is best-effort */ }
  }

  /**
   * Play a clip on the shared element. `src` must already be same-origin
   * rewritten by the caller (sameOriginAudio). meta = {section, taskType, itemId}.
   */
  function play(src, meta) {
    if (!src) return;
    clearWatchdog();
    interrupted = false;
    // Swap-out of the previous clip: mark the pause as ours so onPause
    // doesn't misread it as an interruption.
    expectingSourceChange = true;
    if (!el.paused) { try { el.pause(); } catch {} }
    lastPlay = { src, meta: meta || null };
    currentMeta = meta || null;
    // preload() may have already set + loaded this exact src — skip the
    // reset so the buffered data survives and playback starts instantly.
    // (Trust our own preloadedSrc record: comparing el.src would fail in the
    // browser, where the property getter returns the absolutized URL.)
    if (!(preloadedSrc && preloadedSrc === src)) {
      el.src = src;
      try { el.load(); } catch {}
    }
    preloadedSrc = null;
    currentSrc = src;
    expectingSourceChange = false;
    state = "loading";
    playCalledAt = Date.now();
    watchdogStartedAt = playCalledAt;
    emit({ type: "loading", src, meta: currentMeta });
    armWatchdog(WATCHDOG_INITIAL_MS);

    const p = el.play();
    if (p && typeof p.catch === "function") {
      p.catch((err) => {
        const name = err && err.name;
        if (name === "AbortError") {
          // Normal race: a src swap / pause() interrupted an unresolved
          // play() promise. Never surfaced — but counted for debugging.
          abortErrorCount++;
          return;
        }
        clearWatchdog();
        if (name === "NotAllowedError") {
          state = "blocked";
          emit({ type: "blocked", reason: "not-allowed", src, meta: currentMeta });
          return;
        }
        state = "error";
        emit({
          type: "error",
          errorName: name || "UnknownError",
          mediaErrorCode: el.error ? el.error.code : null,
          readyState: el.readyState,
          networkState: el.networkState,
          src,
          meta: currentMeta,
        });
      });
    }
  }

  /**
   * Warm the element's buffer with the next clip. Only allowed while nothing
   * is (about to be) sounding — never interrupts loading/playing/unlocking.
   */
  function preload(src) {
    if (!src) return;
    if (!(state === "idle" || state === "ended" || state === "error" || state === "blocked")) return;
    expectingSourceChange = true;
    el.src = src;
    try { el.load(); } catch {}
    expectingSourceChange = false;
    preloadedSrc = src;
  }

  /**
   * Retry the last play. Called synchronously from the recovery overlay's
   * click (a fresh gesture, so the browser accepts the play()).
   */
  function retry() {
    if (!unlocked) unlock();
    if (lastPlay) play(lastPlay.src, lastPlay.meta);
  }

  /** Silence the element (e.g. before the mic starts recording). */
  function stop() {
    clearWatchdog();
    expectingSourceChange = true;
    try { el.pause(); } catch {}
    expectingSourceChange = false;
    interrupted = false;
    state = "idle";
  }

  function subscribe(fn) {
    listeners.add(fn);
    return () => listeners.delete(fn);
  }

  function destroy() {
    clearWatchdog();
    el.removeEventListener("playing", onPlaying);
    el.removeEventListener("ended", onEnded);
    el.removeEventListener("error", onError);
    el.removeEventListener("waiting", onWaiting);
    el.removeEventListener("stalled", onWaiting);
    el.removeEventListener("timeupdate", onTimeUpdate);
    el.removeEventListener("pause", onPause);
    document.removeEventListener("visibilitychange", onVisibilityChange);
    listeners.clear();
    currentSrc = null;
    try { el.pause(); } catch {}
    el.src = "";
  }

  return {
    unlock,
    play,
    preload,
    retry,
    stop,
    destroy,
    subscribe,
    getState: () => state,
    getCurrentSrc: () => currentSrc,
    isUnlocked: () => unlocked,
    // Exposed for tests/debugging only — not part of the playback contract.
    _getAbortErrorCount: () => abortErrorCount,
  };
}
