"use client";

/**
 * Exam audio controller — a single persistent (detached) <audio> element that
 * survives the whole exam session.
 *
 * Why: Safari/WebKit grants autoplay permission PER ELEMENT. The old flow
 * mounted a fresh <audio> per question and called play() from setTimeout
 * chains (outside any user-gesture stack), so on iOS Safari / WeChat / QQ
 * browser every question after the first was blocked (NotAllowedError) and
 * the exam went silent. The fix: unlock ONE element with a silent WAV inside
 * the real "start exam" click, then reuse that same element for every clip —
 * an already-unlocked element may be play()ed programmatically on iOS.
 *
 * Framework-free (pure JS class-like factory) so it can be unit-tested
 * without React and shared by the listening + speaking exam shells.
 */

// ~60ms of 8kHz 16-bit mono silence (all-zero PCM), generated by a throwaway
// node script (RIFF/WAVE header + zero-filled data chunk, base64). Used only
// to complete the per-element autoplay unlock inside the start-exam gesture.
const SILENT_WAV =
  "data:audio/wav;base64,UklGRuQDAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACABAAZGF0YcADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

// Watchdog timings. After play() we expect a 'playing' event; if it never
// arrives the user hears nothing and nothing on screen says why. 4s covers a
// slow-but-working start; while the element reports NETWORK_LOADING we extend
// to a 15s total budget (buffering, not blocked) before declaring failure.
const WATCHDOG_INITIAL_MS = 4000;
const WATCHDOG_TOTAL_MS = 15000;

// 解锁静音片(~60ms)理应瞬间落定;这个安全阀兜住「解锁 promise 悬死」的病态
// 情况,保证排队的播放请求最迟 1s 后一定会被执行。
const UNLOCK_FLUSH_SAFETY_MS = 1000;

/**
 * Create an exam audio controller. SSR-safe: on the server returns an inert
 * stub with the same surface so accidental server calls are no-ops.
 */
export function createExamAudioController({ onTelemetry } = {}) {
  if (typeof window === "undefined" || typeof document === "undefined") {
    const noop = () => {};
    return {
      unlock: noop, play: noop, preload: noop, retry: noop, stop: noop,
      destroy: noop, subscribe: () => noop,
      getState: () => "idle", getCurrentSrc: () => null, isUnlocked: () => false,
    };
  }

  // One persistent element, never recreated, so the WebKit per-element unlock
  // survives the whole exam including React remounts of the question
  // components. 挂进 document.body:真机排障发现部分 iOS WebKit 对「从未入
  // DOM 的 audio」假装加载(networkState=2)却永远收不到字节(readyState=0)。
  // 无 controls 的 audio 没有任何视觉,挂进去不可见;挂载失败不致命,退化为
  // 游离元素行为。React 树外的手动挂载不影响任何组件渲染。
  const el = document.createElement("audio");
  el.preload = "auto";
  try {
    if (document.body) document.body.appendChild(el);
  } catch { /* detached fallback */ }

  let state = "idle"; // idle | unlocking | loading | playing | ended | blocked | error
  let unlocked = false;
  let currentSrc = null;
  let currentMeta = null;
  let preloadedSrc = null;
  let lastPlay = null; // { src, meta } — for retry()
  // 解锁进行中到达的播放请求在此排队(见 play() 顶部说明),解锁落定后立即执行。
  let pendingPlay = null; // { src, meta }
  let pendingFlushTimer = null;
  let playCalledAt = 0; // Date.now() at play() — for firstFrameMs
  let watchdogTimer = null;
  let watchdogStartedAt = 0;
  let expectingSourceChange = false; // our own pause/src swap → not an interruption
  let interrupted = false; // paused while page hidden (tab switch / phone call)
  // Debug counter: AbortError is the one error we deliberately swallow (a src
  // swap / pause racing an unresolved play() promise), but we still count it.
  let abortErrorCount = 0;

  const listeners = new Set();

  function emit(event) {
    // Snapshot so a listener unsubscribing mid-loop doesn't skip others.
    for (const fn of Array.from(listeners)) {
      try { fn(event); } catch { /* listener errors must not break playback */ }
    }
    if (onTelemetry) {
      try { onTelemetry(event); } catch { /* telemetry must never throw */ }
    }
  }

  function clearWatchdog() {
    if (watchdogTimer) { clearTimeout(watchdogTimer); watchdogTimer = null; }
  }

  // Arm/extend the silence watchdog. If 'playing' hasn't fired when it goes
  // off: still fetching (NETWORK_LOADING) → report buffering and extend up to
  // the total budget; otherwise (or budget spent) → blocked(silent-timeout).
  //
  // 例外:元素从未解锁且 4s 后仍是 0 字节(readyState=0)——iOS 在无手势时
  // 根本不真正加载(networkState 却显示 2),再等到 15s 也是死等,提前判负让
  // 恢复弹窗尽快出现。真在缓冲的场景(已解锁,或已收到过数据)照旧宽限 15s。
  function armWatchdog(delayMs) {
    clearWatchdog();
    watchdogTimer = setTimeout(() => {
      watchdogTimer = null;
      if (state === "playing") return;
      const elapsed = Date.now() - watchdogStartedAt;
      const genuinelyBuffering = unlocked || el.readyState > 0;
      if (el.networkState === 2 /* NETWORK_LOADING */ && genuinelyBuffering && elapsed < WATCHDOG_TOTAL_MS) {
        emit({ type: "buffering", src: currentSrc, meta: currentMeta });
        armWatchdog(Math.min(WATCHDOG_TOTAL_MS - elapsed, WATCHDOG_TOTAL_MS));
        return;
      }
      state = "blocked";
      emit({
        type: "blocked", reason: "silent-timeout", src: currentSrc, meta: currentMeta,
        networkState: el.networkState, readyState: el.readyState,
      });
    }, delayMs);
  }

  // ── element event wiring (bound once for the controller's lifetime) ──

  function onPlaying() {
    clearWatchdog();
    interrupted = false;
    // 元素真出过声 = WebKit 层面它已经被手势祝福过(或根本不需要):从此程序化
    // play() 可行,等价于解锁完成。覆盖「用户第一下点的就是播放键」的场景——
    // 那次点击的手势直接花在了正片上,SILENT_WAV 解锁从未跑过。
    unlocked = true;
    state = "playing";
    emit({
      type: "playing",
      src: currentSrc,
      meta: currentMeta,
      firstFrameMs: playCalledAt ? Date.now() - playCalledAt : null,
    });
  }

  function onEnded() {
    clearWatchdog();
    state = "ended";
    emit({ type: "ended", src: currentSrc, meta: currentMeta });
  }

  function onError() {
    // Ignore errors for the empty src set by destroy()/stop() teardown.
    if (!currentSrc) return;
    clearWatchdog();
    state = "error";
    emit({
      type: "error",
      errorName: "MediaError",
      mediaErrorCode: el.error ? el.error.code : null,
      readyState: el.readyState,
      networkState: el.networkState,
      src: currentSrc,
      meta: currentMeta,
    });
  }

  function onWaiting() {
    if (state !== "playing" && state !== "loading") return;
    emit({ type: "buffering", src: currentSrc, meta: currentMeta });
  }

  function onTimeUpdate() {
    emit({
      type: "progress",
      currentTime: el.currentTime,
      duration: el.duration,
      src: currentSrc,
      meta: currentMeta,
    });
  }

  function onPause() {
    // A pause we didn't cause, before 'ended', while the page is hidden =
    // the OS/browser cut us off (tab switch, phone call, screen lock).
    if (expectingSourceChange || state === "ended") return;
    if (document.visibilityState === "hidden") interrupted = true;
  }

  function onVisibilityChange() {
    if (document.visibilityState !== "visible") return;
    if (interrupted && state !== "ended") {
      interrupted = false;
      state = "blocked";
      emit({
        type: "blocked", reason: "interrupted", src: currentSrc, meta: currentMeta,
        networkState: el.networkState, readyState: el.readyState,
      });
    }
  }

  el.addEventListener("playing", onPlaying);
  el.addEventListener("ended", onEnded);
  el.addEventListener("error", onError);
  el.addEventListener("waiting", onWaiting);
  el.addEventListener("stalled", onWaiting);
  el.addEventListener("timeupdate", onTimeUpdate);
  el.addEventListener("pause", onPause);
  document.addEventListener("visibilitychange", onVisibilityChange);

  // ── public API ──

  /**
   * Unlock the element. MUST be called synchronously inside a user gesture
   * (the start-exam click). Idempotent. Also pre-unlocks speechSynthesis so
   * the TTS fallback can speak later without its own gesture.
   *
   * Returns true when the unlock was actually attempted (or was already done),
   * false when it was skipped by the anti-interrupt gate below. Callers that
   * manage a first-interaction listener (ExamAudioProvider) use the return
   * value to decide whether to keep listening for another gesture.
   */
  function unlock() {
    if (unlocked) return true;
    // Anti-interrupt gate: never swap in SILENT_WAV while a real clip is
    // loading or sounding. On practice pages the sentence auto-plays with zero
    // clicks, and the first-interaction unlock can land mid-playback — doing
    // el.src = SILENT_WAV; el.play() there would 腰斩 the题干. Skip ONLY while
    // loading/playing; every other state (idle/ended/blocked/error) unlocks
    // normally — critically, an iOS autoplay-blocked clip sits in "blocked",
    // so the unlock can still complete on the next gesture instead of being
    // stuck forever (the persistent-player disease we must not revive).
    if (state === "loading" || state === "playing") return false;
    // 已有一次解锁在途:别重启(重启会 AbortError 掉在途那次,谁也完不成)。
    if (state === "unlocking") return true;
    state = "unlocking";
    try {
      el.src = SILENT_WAV;
      const p = el.play();
      if (p && typeof p.then === "function") {
        p.then(() => {
          unlocked = true;
          if (state === "unlocking") state = "idle";
          emit({ type: "unlocked" });
          flushPendingPlay();
        }).catch((err) => {
          if (err && err.name === "AbortError") { abortErrorCount++; flushPendingPlay(); return; }
          if (state === "unlocking") state = "idle";
          emit({ type: "unlock-blocked", errorName: err && err.name });
          flushPendingPlay();
        });
      } else {
        // Very old engines return undefined from play() — assume it worked.
        unlocked = true;
        state = "idle";
        emit({ type: "unlocked" });
        flushPendingPlay();
      }
    } catch (err) {
      state = "idle";
      emit({ type: "unlock-blocked", errorName: err && err.name });
      flushPendingPlay();
    }
    // Pre-unlock iOS speechSynthesis for the TTS fallback: a near-empty
    // utterance spoken inside the gesture, cancelled immediately.
    try {
      if (typeof speechSynthesis !== "undefined" && typeof SpeechSynthesisUtterance !== "undefined") {
        speechSynthesis.speak(new SpeechSynthesisUtterance(" "));
        speechSynthesis.cancel();
      }
    } catch { /* feature-detect only; TTS unlock is best-effort */ }
    return true;
  }

  // 解锁落定后补播排队的请求。安全阀计时器一并清掉。
  function flushPendingPlay() {
    if (pendingFlushTimer) { clearTimeout(pendingFlushTimer); pendingFlushTimer = null; }
    if (!pendingPlay) return;
    const q = pendingPlay;
    pendingPlay = null;
    play(q.src, q.meta);
  }

  /**
   * Play a clip on the shared element. `src` must already be same-origin
   * rewritten by the caller (sameOriginAudio). meta = {section, taskType, itemId}.
   */
  function play(src, meta) {
    if (!src) return;
    // 手势内的解锁静音片正在途中(retry()/首次交互解锁与播放同 tick 到达的场景):
    // 此刻换 src 会把解锁腰斩成 AbortError——unlocked 永远置不上,而且这次手势
    // 已被静音片消耗,真正的 play() 反而变成无手势调用被 iOS 拒绝(「继续考试」
    // 点了没反应的根因)。排队,解锁一落定(~60ms)立即在已祝福的元素上续播。
    if (state === "unlocking") {
      pendingPlay = { src, meta: meta || null };
      lastPlay = { src, meta: meta || null };
      currentMeta = meta || null;
      emit({ type: "loading", src, meta: currentMeta });
      if (!pendingFlushTimer) {
        pendingFlushTimer = setTimeout(() => {
          pendingFlushTimer = null;
          if (state === "unlocking") state = "idle"; // 解锁悬死,放弃等待
          flushPendingPlay();
        }, UNLOCK_FLUSH_SAFETY_MS);
      }
      return;
    }
    clearWatchdog();
    interrupted = false;
    // Swap-out of the previous clip: mark the pause as ours so onPause
    // doesn't misread it as an interruption.
    expectingSourceChange = true;
    if (!el.paused) { try { el.pause(); } catch {} }
    lastPlay = { src, meta: meta || null };
    currentMeta = meta || null;
    // preload() may have already set + loaded this exact src — skip the
    // reset so the buffered data survives and playback starts instantly.
    // (Trust our own preloadedSrc record: comparing el.src would fail in the
    // browser, where the property getter returns the absolutized URL.)
    if (!(preloadedSrc && preloadedSrc === src)) {
      el.src = src;
      try { el.load(); } catch {}
    }
    preloadedSrc = null;
    currentSrc = src;
    expectingSourceChange = false;
    state = "loading";
    playCalledAt = Date.now();
    watchdogStartedAt = playCalledAt;
    emit({ type: "loading", src, meta: currentMeta });
    armWatchdog(WATCHDOG_INITIAL_MS);

    const p = el.play();
    if (p && typeof p.catch === "function") {
      p.catch((err) => {
        const name = err && err.name;
        if (name === "AbortError") {
          // Normal race: a src swap / pause() interrupted an unresolved
          // play() promise. Never surfaced — but counted for debugging.
          abortErrorCount++;
          return;
        }
        clearWatchdog();
        if (name === "NotAllowedError") {
          state = "blocked";
          emit({
            type: "blocked", reason: "not-allowed", src, meta: currentMeta,
            networkState: el.networkState, readyState: el.readyState,
          });
          return;
        }
        state = "error";
        emit({
          type: "error",
          errorName: name || "UnknownError",
          mediaErrorCode: el.error ? el.error.code : null,
          readyState: el.readyState,
          networkState: el.networkState,
          src,
          meta: currentMeta,
        });
      });
    }
  }

  /**
   * Warm the element's buffer with the next clip. Only allowed while nothing
   * is (about to be) sounding — never interrupts loading/playing/unlocking.
   */
  function preload(src) {
    if (!src) return;
    if (!(state === "idle" || state === "ended" || state === "error" || state === "blocked")) return;
    expectingSourceChange = true;
    el.src = src;
    try { el.load(); } catch {}
    expectingSourceChange = false;
    preloadedSrc = src;
  }

  /**
   * Retry the last play. Called synchronously from the recovery overlay's
   * click (a fresh gesture, so the browser accepts the play()).
   *
   * 整个手势直接花在正片上——绝不先播解锁静音片。iOS 一次手势只祝福一次媒体
   * 播放:静音片抢跑会把手势耗光,正片沦为无手势加载(0 字节死等 15s,真机
   * 实锤 net=2 rdy=0),按钮看起来就是坏的。正片在手势内 play() 与用户点直链
   * 同级,必然放行;它一出声 onPlaying 就把元素标记为已解锁,后续自动连播走
   * 程序化播放。lastPlay 为空(理论不可达)才退回纯解锁。
   */
  function retry() {
    if (lastPlay) {
      play(lastPlay.src, lastPlay.meta);
      return;
    }
    if (!unlocked) unlock();
  }

  /** Silence the element (e.g. before the mic starts recording). */
  function stop() {
    clearWatchdog();
    if (pendingFlushTimer) { clearTimeout(pendingFlushTimer); pendingFlushTimer = null; }
    pendingPlay = null;
    expectingSourceChange = true;
    try { el.pause(); } catch {}
    expectingSourceChange = false;
    interrupted = false;
    state = "idle";
  }

  function subscribe(fn) {
    listeners.add(fn);
    return () => listeners.delete(fn);
  }

  function destroy() {
    clearWatchdog();
    if (pendingFlushTimer) { clearTimeout(pendingFlushTimer); pendingFlushTimer = null; }
    pendingPlay = null;
    el.removeEventListener("playing", onPlaying);
    el.removeEventListener("ended", onEnded);
    el.removeEventListener("error", onError);
    el.removeEventListener("waiting", onWaiting);
    el.removeEventListener("stalled", onWaiting);
    el.removeEventListener("timeupdate", onTimeUpdate);
    el.removeEventListener("pause", onPause);
    document.removeEventListener("visibilitychange", onVisibilityChange);
    listeners.clear();
    currentSrc = null;
    try { el.pause(); } catch {}
    el.src = "";
    try { if (el.parentNode) el.parentNode.removeChild(el); } catch {}
  }

  return {
    unlock,
    play,
    preload,
    retry,
    stop,
    destroy,
    subscribe,
    getState: () => state,
    getCurrentSrc: () => currentSrc,
    isUnlocked: () => unlocked,
    // Exposed for tests/debugging only — not part of the playback contract.
    _getAbortErrorCount: () => abortErrorCount,
  };
}
