#!/usr/bin/env node
// Universal merge script for items generated by the Claude routine.
// Reads a staging file (the routine's output), validates against the same
// quality gates the existing DeepSeek pipeline uses, and appends valid items
// to the production bank.
//
// Usage:
//   node scripts/mergeClaude.mjs <bank> <staging-file>
//   bank ∈ { bs, disc, email }
//
// Staging file format:
//   { "items": [ ...array of items in the bank's schema... ] }
//
// Reading (AP / CTW / RDL) merges should use the existing
// scripts/merge-staging.mjs which already handles those banks.
//
// Exit codes: 0 = success, 1 = error, 2 = no items merged (still success in
// the routine's view — staging committed but bank unchanged)

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { createRequire } from "module";

const __dirname = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const ROOT = resolve(__dirname, "..");

const { validateQuestion, validateQuestionSet } = require("../lib/questionBank/buildSentenceSchema.js");
const { validateAllSets } = require("./validate-bank.js");

// NEWBANK_ROOT (optional): when set (e.g. NEWBANK_ROOT=data/newBank), validated items are
// appended to the NEW bank under that root instead of the live bank, so a fresh bank can be
// staged for a one-shot replacement without touching production. Default (unset) = live bank.
const NEWBANK_ROOT = (process.env.NEWBANK_ROOT || "").trim()
  ? resolve(ROOT, (process.env.NEWBANK_ROOT || "").trim())
  : null;
function bankFilePath(relFromData) {
  return NEWBANK_ROOT ? resolve(NEWBANK_ROOT, relFromData) : resolve(ROOT, "data", relFromData);
}
if (NEWBANK_ROOT) console.log(`NEWBANK_ROOT set → writing bank to ${NEWBANK_ROOT} (live bank untouched)`);

const bank = String(process.argv[2] || "").trim();
const stagingFile = process.argv[3];

if (!bank || !stagingFile) {
  console.error("Usage: node scripts/mergeClaude.mjs <bank> <staging-file>");
  console.error("bank ∈ { bs, disc, email }");
  process.exit(1);
}

function readJSON(p) {
  return JSON.parse(readFileSync(p, "utf8"));
}

function writeJSON(p, data) {
  writeFileSync(p, JSON.stringify(data, null, 2) + "\n", "utf8");
}

// ── BS merge ──────────────────────────────────────────────────────────
// Claude writes 10-20 BS items. We split into sets of 10, validate each set
// against the existing quality gate, and append to data/buildSentence/questions.json.
function mergeBS(stagingPath) {
  const staging = readJSON(stagingPath);
  const items = Array.isArray(staging.items) ? staging.items : Array.isArray(staging) ? staging : [];
  if (items.length === 0) {
    console.log("BS staging file has 0 items.");
    process.exit(2);
  }

  // Per-item hard validation (drops malformed)
  const accepted = [];
  const rejected = [];
  for (const q of items) {
    const v = validateQuestion(q);
    if (v.fatal.length > 0 || v.format.length > 0) {
      rejected.push({ id: q.id, fatal: v.fatal, format: v.format });
      continue;
    }
    accepted.push(q);
  }
  console.log(`BS: ${accepted.length}/${items.length} items passed per-item validation`);
  if (rejected.length > 0) {
    console.log("  rejection samples:");
    rejected.slice(0, 5).forEach((r) => console.log(`    - id=${r.id} fatal=${(r.fatal || []).join("|")} format=${(r.format || []).join("|")}`));
  }
  if (accepted.length < 10) {
    console.log(`Not enough valid items to form a 10-question set. Skipping merge.`);
    process.exit(2);
  }

  // Compose sets of exactly 10
  const bankPath = bankFilePath("buildSentence/questions.json");
  const prod = readJSON(bankPath);
  const existingSets = prod.question_sets || [];
  const nextSetId = existingSets.length > 0 ? Math.max(...existingSets.map((s) => s.set_id || 0)) + 1 : 1;

  const newSets = [];
  for (let i = 0; i + 10 <= accepted.length; i += 10) {
    const setId = nextSetId + newSets.length;
    const setItems = accepted.slice(i, i + 10).map((q, qi) => ({ ...q, id: `ets_s${setId}_q${qi + 1}` }));
    const set = { set_id: setId, questions: setItems };
    const v = validateQuestionSet(set);
    if (!v.ok) {
      console.log(`Set ${setId} failed set-level validation: ${v.reasons?.join("; ") || "unknown"}`);
      continue;
    }
    newSets.push(set);
  }
  if (newSets.length === 0) {
    console.log("No valid 10-question sets could be assembled.");
    process.exit(2);
  }

  // Strict-validate the new sets (catches subtle issues)
  const newOnly = { version: "1.3", generated_at: new Date().toISOString(), question_sets: newSets };
  const check = validateAllSets(newOnly, { strict: true });
  if (!check.ok) {
    console.error("New sets failed strict validation:");
    [...check.failures, ...check.strictHardFails.map((x) => `${x.label}: ${x.reasons.join("; ")}`)].forEach((x) => console.error("  - " + x));
    process.exit(1);
  }
  check.strictWarnings.forEach((x) => console.warn(`WARN ${x.label}: ${x.reasons.join("; ")}`));

  // Append + write
  const merged = {
    version: "1.3",
    generated_at: new Date().toISOString(),
    question_sets: [...existingSets, ...newSets],
  };
  writeJSON(bankPath, merged);
  console.log(`✅ Appended ${newSets.length} set(s) (set_id ${newSets[0].set_id}–${newSets[newSets.length - 1].set_id}) to ${bankPath}`);
  console.log(`   Total sets now: ${merged.question_sets.length}`);
  process.exit(0);
}

// ── Discussion merge ─────────────────────────────────────────────────
function normalizeDiscItem(q) {
  if (!q || typeof q !== "object") return null;
  const professorText = String(q?.professor?.text || "").trim();
  const students = Array.isArray(q.students) ? q.students.filter((s) => s && s.name && s.text) : [];
  if (!professorText || students.length < 2) return null;
  const course = String(q.course || "").trim();
  if (!course) return null;
  return {
    course,
    professor: { name: String(q.professor.name || "Professor").trim(), text: professorText },
    students: students.slice(0, 2).map((s) => ({ name: String(s.name).trim(), text: String(s.text).trim() })),
  };
}

function mergeDisc(stagingPath) {
  const staging = readJSON(stagingPath);
  const items = Array.isArray(staging.items) ? staging.items : Array.isArray(staging) ? staging : [];

  const bankPath = bankFilePath("academicWriting/prompts.json");
  const prod = readJSON(bankPath);
  const existingIds = new Set((prod || []).map((q) => q.id).filter(Boolean));
  const nextN = (prod || []).length > 0
    ? Math.max(...(prod || []).map((q) => Number((q.id || "").replace(/^ad/, "")) || 0)) + 1
    : 1;

  const accepted = [];
  const rejected = [];
  let counter = nextN;
  for (const q of items) {
    const norm = normalizeDiscItem(q);
    if (!norm) {
      rejected.push({ reason: "schema_invalid", q });
      continue;
    }
    // Dedup by exact professor text match (within an existing item)
    const dup = (prod || []).find((p) => String(p?.professor?.text || "").trim() === norm.professor.text);
    if (dup) {
      rejected.push({ reason: "duplicate_text", id: dup.id });
      continue;
    }
    accepted.push({ id: `ad${counter}`, ...norm });
    counter += 1;
  }
  console.log(`Discussion: ${accepted.length}/${items.length} items accepted`);
  rejected.slice(0, 5).forEach((r) => console.log(`  - rejected: ${r.reason}`));
  if (accepted.length === 0) process.exit(2);

  const merged = [...(prod || []), ...accepted];
  writeJSON(bankPath, merged);
  console.log(`✅ Appended ${accepted.length} Discussion item(s) to ${bankPath} (total now ${merged.length})`);
  process.exit(0);
}

// ── Email merge ──────────────────────────────────────────────────────
const EMAIL_TOPIC_NORM = {
  "職場工作": "职场工作",
  "社區生活": "社区生活",
  "消費售後": "消费售后",
};
function normalizeEmailItem(q) {
  if (!q || typeof q !== "object") return null;
  const scenario = String(q.scenario || "").trim();
  const direction = String(q.direction || "").trim();
  const goals = Array.isArray(q.goals)
    ? q.goals.map((g) => String(g || "").trim()).filter(Boolean).slice(0, 3)
    : [];
  if (!scenario || !direction || goals.length !== 3) return null;
  const to = String(q.to || "").trim();
  const subject = String(q.subject || "").trim();
  const topic = String(q.topic || "").trim();
  if (!to || !subject || !topic) return null;
  return {
    topic: EMAIL_TOPIC_NORM[topic] || topic,
    scenario,
    direction,
    goals,
    to,
    subject,
  };
}

function mergeEmail(stagingPath) {
  const staging = readJSON(stagingPath);
  const items = Array.isArray(staging.items) ? staging.items : Array.isArray(staging) ? staging : [];

  const bankPath = bankFilePath("emailWriting/prompts.json");
  const prod = readJSON(bankPath);
  const nextN = (prod || []).length > 0
    ? Math.max(...(prod || []).map((q) => Number((q.id || "").replace(/^em/, "")) || 0)) + 1
    : 1;

  const accepted = [];
  const rejected = [];
  let counter = nextN;
  for (const q of items) {
    const norm = normalizeEmailItem(q);
    if (!norm) {
      rejected.push({ reason: "schema_invalid" });
      continue;
    }
    // Dedup by scenario match
    const dup = (prod || []).find((p) => String(p?.scenario || "").trim() === norm.scenario);
    if (dup) {
      rejected.push({ reason: "duplicate_scenario", id: dup.id });
      continue;
    }
    accepted.push({ id: `em${counter}`, ...norm });
    counter += 1;
  }
  console.log(`Email: ${accepted.length}/${items.length} items accepted`);
  rejected.slice(0, 5).forEach((r) => console.log(`  - rejected: ${r.reason}`));
  if (accepted.length === 0) process.exit(2);

  const merged = [...(prod || []), ...accepted];
  writeJSON(bankPath, merged);
  console.log(`✅ Appended ${accepted.length} Email item(s) to ${bankPath} (total now ${merged.length})`);
  process.exit(0);
}

// ── Dispatch ─────────────────────────────────────────────────────────
const dispatcher = { bs: mergeBS, disc: mergeDisc, email: mergeEmail };
if (!dispatcher[bank]) {
  console.error(`Unknown bank "${bank}". Valid: ${Object.keys(dispatcher).join(", ")}`);
  process.exit(1);
}
dispatcher[bank](stagingFile);
