#!/usr/bin/env node
// Universal merge script for items generated by the Claude routine.
// Reads a staging file (the routine's output), validates against the same
// quality gates the existing DeepSeek pipeline uses, and appends valid items
// to the production bank.
//
// Usage:
//   node scripts/mergeClaude.mjs <bank> <staging-file>
//   bank ∈ { bs, disc, email }
//
// Staging file format:
//   { "items": [ ...array of items in the bank's schema... ] }
//
// Reading (AP / CTW / RDL) merges should use the existing
// scripts/merge-staging.mjs which already handles those banks.
//
// Exit codes: 0 = success, 1 = error, 2 = no items merged (still success in
// the routine's view — staging committed but bank unchanged)

import { readFileSync, writeFileSync, rmSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { createRequire } from "module";
import { execSync } from "child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const ROOT = resolve(__dirname, "..");

const { validateQuestion, validateQuestionSet } = require("../lib/questionBank/buildSentenceSchema.js");
const { validateAllSets } = require("./validate-bank.js");
// 2026-07-11 范式硬拒白名单(实弹证明散文规则约束不住模型:em300 裸机构收件人、
// marine biology 课程泄漏)。全部为精度 1.0 的确定性检查,不合格拒题交 R2 重试。
const { DISC_COURSE_LIST, DISC_STUDENT_NAMES } = await import("../lib/ai/prompts/academicWriting.js");
const EMAIL_RECIPIENT_OK = (to) => /^(Mr|Ms|Mrs|Dr|Prof(essor)?)\.?\s+[A-Z][a-zA-Z'-]+$/.test(to) || /^[A-Z][a-z]+$/.test(to);
const DISC_PROF_OK = (name) => /^Dr\. (Gupta|Diaz|Achebe)$/.test(String(name || ""));
// 合库层通用内容去重（exact 指纹 + jaccard 近重复）。
const { createDedupIndex, checkDuplicate, addToIndex } = require("../lib/gen/contentDedup.js");

// NEWBANK_ROOT (optional): when set (e.g. NEWBANK_ROOT=data/newBank), validated items are
// appended to the NEW bank under that root instead of the live bank, so a fresh bank can be
// staged for a one-shot replacement without touching production. Default (unset) = live bank.
const NEWBANK_ROOT = (process.env.NEWBANK_ROOT || "").trim()
  ? resolve(ROOT, (process.env.NEWBANK_ROOT || "").trim())
  : null;
function bankFilePath(relFromData) {
  return NEWBANK_ROOT ? resolve(NEWBANK_ROOT, relFromData) : resolve(ROOT, "data", relFromData);
}
if (NEWBANK_ROOT) console.log(`NEWBANK_ROOT set → writing bank to ${NEWBANK_ROOT} (live bank untouched)`);

const bank = String(process.argv[2] || "").trim();
const stagingFile = process.argv[3];

if (!bank || !stagingFile) {
  console.error("Usage: node scripts/mergeClaude.mjs <bank> <staging-file>");
  console.error("bank ∈ { bs, disc, email }");
  process.exit(1);
}

function readJSON(p) {
  return JSON.parse(readFileSync(p, "utf8"));
}

function writeJSON(p, data) {
  writeFileSync(p, JSON.stringify(data, null, 2) + "\n", "utf8");
}

// ── BS merge ──────────────────────────────────────────────────────────
// Claude writes 10-20 BS items. We split into sets of 10, validate each set
// against the existing quality gate, and append to data/buildSentence/questions.json.
function mergeBS(stagingPath) {
  const staging = readJSON(stagingPath);
  const items = Array.isArray(staging.items) ? staging.items : Array.isArray(staging) ? staging : [];
  if (items.length === 0) {
    console.log("BS staging file has 0 items.");
    process.exit(2);
  }

  // Per-item hard validation (drops malformed)
  const accepted = [];
  const rejected = [];
  for (const q of items) {
    const v = validateQuestion(q);
    if (v.fatal.length > 0 || v.format.length > 0) {
      rejected.push({ id: q.id, fatal: v.fatal, format: v.format });
      continue;
    }
    accepted.push(q);
  }
  console.log(`BS: ${accepted.length}/${items.length} items passed per-item validation`);
  if (rejected.length > 0) {
    console.log("  rejection samples:");
    rejected.slice(0, 5).forEach((r) => console.log(`    - id=${r.id} fatal=${(r.fatal || []).join("|")} format=${(r.format || []).join("|")}`));
  }

  // ── Answer content dedup (exact fingerprint + jaccard ≥ 0.75) ─────────────
  // mergeBS previously did NO answer dedup (only the GENERATION path in
  // generateBSQuestions.mjs deduped answers) — a routine could ship a set that
  // duplicates a live-bank sentence or repeats itself. We drop near/exact-dup
  // answers INDIVIDUALLY (mirroring the per-item validation-reject semantics
  // above), then compose sets from the survivors. Seeded from live-bank answers
  // and grown per accepted item so within-batch repeats are caught too.
  let bankAnswerItems = [];
  try {
    const existingBank = readJSON(bankFilePath("buildSentence/questions.json"));
    bankAnswerItems = (existingBank.question_sets || []).flatMap((s) => s.questions || []);
  } catch (_) { bankAnswerItems = []; } // fail-open: unreadable bank → no dedup (never blocks merge)
  const bsIndex = createDedupIndex(bankAnswerItems, "bs");
  const deduped = [];
  let bsContentDup = 0;
  for (const q of accepted) {
    const dup = checkDuplicate(bsIndex, q, "bs"); // threshold defaults to 0.75 for bs
    if (dup.dup) {
      bsContentDup++;
      console.log(`  skip content-dup answer ${q.id || "(no-id)"} ~= ${dup.matchId} (${dup.reason})`);
      continue;
    }
    addToIndex(bsIndex, q, "bs");
    deduped.push(q);
  }
  if (bsContentDup > 0) console.log(`BS: ${bsContentDup} near/exact-duplicate answer(s) dropped (content dedup); ${deduped.length} remain`);
  accepted.length = 0;
  accepted.push(...deduped);

  if (accepted.length < 10) {
    console.log(`Not enough valid items to form a 10-question set. Skipping merge.`);
    process.exit(2);
  }

  // Compose sets of exactly 10
  const bankPath = bankFilePath("buildSentence/questions.json");
  const prod = readJSON(bankPath);
  const existingSets = prod.question_sets || [];
  const nextSetId = existingSets.length > 0 ? Math.max(...existingSets.map((s) => s.set_id || 0)) + 1 : 1;

  const newSets = [];
  for (let i = 0; i + 10 <= accepted.length; i += 10) {
    const setId = nextSetId + newSets.length;
    const setItems = accepted.slice(i, i + 10).map((q, qi) => ({ ...q, id: `ets_s${setId}_q${qi + 1}` }));
    const set = { set_id: setId, questions: setItems };
    const v = validateQuestionSet(set);
    if (!v.ok) {
      console.log(`Set ${setId} failed set-level validation: ${v.reasons?.join("; ") || "unknown"}`);
      continue;
    }
    newSets.push(set);
  }
  if (newSets.length === 0) {
    console.log("No valid 10-question sets could be assembled.");
    process.exit(2);
  }

  // Strict-validate the new sets (catches subtle issues)
  const newOnly = { version: "1.3", generated_at: new Date().toISOString(), question_sets: newSets };
  const check = validateAllSets(newOnly, { strict: true });
  if (!check.ok) {
    console.error("New sets failed strict validation:");
    [...check.failures, ...check.strictHardFails.map((x) => `${x.label}: ${x.reasons.join("; ")}`)].forEach((x) => console.error("  - " + x));
    process.exit(1);
  }
  check.strictWarnings.forEach((x) => console.warn(`WARN ${x.label}: ${x.reasons.join("; ")}`));

  // Append (compose the merged bank in memory first — do NOT write yet)
  const merged = {
    version: "1.3",
    generated_at: new Date().toISOString(),
    question_sets: [...existingSets, ...newSets],
  };

  // ── Anti-regression difficulty gate (frozen real-exam standard) ──────────
  // 2026-06-16: the frozen difficulty gate (scripts/bs-difficulty-scorer.mjs --gate)
  // used to run ONLY in the offline bs-accept.mjs, so this nightly/Claude merge path
  // shipped BS items WITHOUT ever checking them against the real-exam standard — the
  // exact hole that let the live bank drift out of calibration. We now gate every BS
  // merge here, on the would-be-merged bank, BEFORE committing it.
  //   - Default (since 2026-06-17, live bank now gate-clean): ENFORCE — a FAIL refuses
  //     the merge and leaves the bank untouched.
  //   - BS_GATE_ENFORCE=0: warning-only escape hatch (logs the verdict, still merges).
  const gateTmp = bankPath + ".gatecheck.tmp";
  writeJSON(gateTmp, merged);
  let gatePass = true;
  try {
    execSync(`node ${resolve(ROOT, "scripts/bs-difficulty-scorer.mjs")} --gate ${gateTmp}`, { stdio: "inherit" });
  } catch { gatePass = false; }
  // Enforce by DEFAULT as of 2026-06-17 (the live bank is now gate-clean). Opt out with
  // BS_GATE_ENFORCE=0 for a warning-only run. Default-on is what locks the PRIMARY path:
  // the claude.ai R1/R2 routine calls this script and its env can't be edited from the
  // repo, so making enforcement the code default locks it without a routine-side change.
  const enforceGate = (process.env.BS_GATE_ENFORCE || "1").trim() !== "0";
  if (!gatePass && enforceGate) {
    rmSync(gateTmp, { force: true });
    console.error("✗ BS 难度冻结门 FAIL → 拒绝合库，live 题库未改动（默认强制；BS_GATE_ENFORCE=0 可临时改回仅警告）。先把漂移维度修回真题带内再重跑。");
    process.exit(1);
  }
  rmSync(gateTmp, { force: true });

  // Commit
  writeJSON(bankPath, merged);
  console.log(`✅ Appended ${newSets.length} set(s) (set_id ${newSets[0].set_id}–${newSets[newSets.length - 1].set_id}) to ${bankPath}`);
  console.log(`   Total sets now: ${merged.question_sets.length}`);
  if (gatePass) console.log("✓ BS 难度冻结门 PASS");
  else console.warn("⚠ BS 难度冻结门 FAIL（BS_GATE_ENFORCE=0 → 仅警告，本次仍合库）。");
  process.exit(0);
}

// ── Discussion merge ─────────────────────────────────────────────────
function normalizeDiscItem(q) {
  if (!q || typeof q !== "object") return null;
  const professorText = String(q?.professor?.text || "").trim();
  const students = Array.isArray(q.students) ? q.students.filter((s) => s && s.name && s.text) : [];
  if (!professorText || students.length < 2) return null;
  const course = String(q.course || "").trim();
  if (!course) return null;
  return {
    course,
    professor: { name: String(q.professor.name || "Professor").trim(), text: professorText },
    students: students.slice(0, 2).map((s) => ({ name: String(s.name).trim(), text: String(s.text).trim() })),
  };
}

function mergeDisc(stagingPath) {
  const staging = readJSON(stagingPath);
  const items = Array.isArray(staging.items) ? staging.items : Array.isArray(staging) ? staging : [];

  const bankPath = bankFilePath("academicWriting/prompts.json");
  const prod = readJSON(bankPath);
  const existingIds = new Set((prod || []).map((q) => q.id).filter(Boolean));
  const nextN = (prod || []).length > 0
    ? Math.max(...(prod || []).map((q) => Number((q.id || "").replace(/^ad/, "")) || 0)) + 1
    : 1;

  // Content dedup on professor text: exact fingerprint + near jaccard (0.8). Seeded from
  // the live bank and grown per accepted item — so it also catches within-batch repeats,
  // which the exact `.find(prod)` below never did (it only compared against the live bank).
  const discIndex = createDedupIndex(prod || [], "discussion");

  const accepted = [];
  const rejected = [];
  let counter = nextN;
  let contentDupCount = 0;
  for (const q of items) {
    const norm = normalizeDiscItem(q);
    if (!norm) {
      rejected.push({ reason: "schema_invalid", q });
      continue;
    }
    // 范式硬拒:课程白名单 / 四人名字池 / 三教授姓氏(真题实测的封闭集合)
    if (!DISC_COURSE_LIST.includes(String(norm.course || ""))) {
      rejected.push({ reason: "course_not_in_whitelist", course: norm.course });
      continue;
    }
    if (!(norm.students || []).every((s) => DISC_STUDENT_NAMES.includes(s.name))) {
      rejected.push({ reason: "student_name_not_in_pool", names: (norm.students || []).map((s) => s.name) });
      continue;
    }
    if (!DISC_PROF_OK(norm.professor?.name)) {
      rejected.push({ reason: "professor_name_not_in_pool", name: norm.professor?.name });
      continue;
    }
    // Dedup by exact professor text match (within an existing item)
    const dup = (prod || []).find((p) => String(p?.professor?.text || "").trim() === norm.professor.text);
    if (dup) {
      rejected.push({ reason: "duplicate_text", id: dup.id });
      continue;
    }
    // Fuzzy + within-batch dedup on professor text.
    const cdup = checkDuplicate(discIndex, norm, "discussion");
    if (cdup.dup) {
      contentDupCount++;
      rejected.push({ reason: `content_dup_${cdup.reason}`, id: cdup.matchId });
      continue;
    }
    const accItem = { id: `ad${counter}`, ...norm };
    addToIndex(discIndex, accItem, "discussion");
    accepted.push(accItem);
    counter += 1;
  }
  console.log(`Discussion: ${accepted.length}/${items.length} items accepted${contentDupCount ? ` (${contentDupCount} content-dup skipped)` : ""}`);
  rejected.slice(0, 5).forEach((r) => console.log(`  - rejected: ${r.reason}`));
  if (accepted.length === 0) process.exit(2);

  const merged = [...(prod || []), ...accepted];
  writeJSON(bankPath, merged);
  console.log(`✅ Appended ${accepted.length} Discussion item(s) to ${bankPath} (total now ${merged.length})`);
  process.exit(0);
}

// ── Email merge ──────────────────────────────────────────────────────
const EMAIL_TOPIC_NORM = {
  "職場工作": "职场工作",
  "社區生活": "社区生活",
  "消費售後": "消费售后",
};
function normalizeEmailItem(q) {
  if (!q || typeof q !== "object") return null;
  const scenario = String(q.scenario || "").trim();
  const direction = String(q.direction || "").trim();
  const goals = Array.isArray(q.goals)
    ? q.goals.map((g) => String(g || "").trim()).filter(Boolean).slice(0, 3)
    : [];
  if (!scenario || !direction || goals.length !== 3) return null;
  const to = String(q.to || "").trim();
  const subject = String(q.subject || "").trim();
  const topic = String(q.topic || "").trim();
  if (!to || !subject || !topic) return null;
  return {
    topic: EMAIL_TOPIC_NORM[topic] || topic,
    scenario,
    direction,
    goals,
    to,
    subject,
  };
}

function mergeEmail(stagingPath) {
  const staging = readJSON(stagingPath);
  const items = Array.isArray(staging.items) ? staging.items : Array.isArray(staging) ? staging : [];

  const bankPath = bankFilePath("emailWriting/prompts.json");
  const prod = readJSON(bankPath);
  const nextN = (prod || []).length > 0
    ? Math.max(...(prod || []).map((q) => Number((q.id || "").replace(/^em/, "")) || 0)) + 1
    : 1;

  // Content dedup on scenario: exact fingerprint + near jaccard (0.8). Seeded from the live
  // bank and grown per accepted item — also catches within-batch repeats, which the exact
  // `.find(prod)` below never did.
  const emailIndex = createDedupIndex(prod || [], "email");

  const accepted = [];
  const rejected = [];
  let counter = nextN;
  let contentDupCount = 0;
  for (const q of items) {
    const norm = normalizeEmailItem(q);
    if (!norm) {
      rejected.push({ reason: "schema_invalid" });
      continue;
    }
    // 范式硬拒:收件人只允许 Title+Surname 或朋友 first name(真题仅此两式)
    if (!EMAIL_RECIPIENT_OK(String(norm.to || ""))) {
      rejected.push({ reason: "recipient_form", to: norm.to });
      continue;
    }
    // Dedup by scenario match
    const dup = (prod || []).find((p) => String(p?.scenario || "").trim() === norm.scenario);
    if (dup) {
      rejected.push({ reason: "duplicate_scenario", id: dup.id });
      continue;
    }
    // Fuzzy + within-batch dedup on scenario.
    const cdup = checkDuplicate(emailIndex, norm, "email");
    if (cdup.dup) {
      contentDupCount++;
      rejected.push({ reason: `content_dup_${cdup.reason}`, id: cdup.matchId });
      continue;
    }
    const accItem = { id: `em${counter}`, ...norm };
    addToIndex(emailIndex, accItem, "email");
    accepted.push(accItem);
    counter += 1;
  }
  console.log(`Email: ${accepted.length}/${items.length} items accepted${contentDupCount ? ` (${contentDupCount} content-dup skipped)` : ""}`);
  rejected.slice(0, 5).forEach((r) => console.log(`  - rejected: ${r.reason}`));
  if (accepted.length === 0) process.exit(2);

  const merged = [...(prod || []), ...accepted];
  writeJSON(bankPath, merged);
  console.log(`✅ Appended ${accepted.length} Email item(s) to ${bankPath} (total now ${merged.length})`);
  process.exit(0);
}

// ── Dispatch ─────────────────────────────────────────────────────────
const dispatcher = { bs: mergeBS, disc: mergeDisc, email: mergeEmail };
if (!dispatcher[bank]) {
  console.error(`Unknown bank "${bank}". Valid: ${Object.keys(dispatcher).join(", ")}`);
  process.exit(1);
}
dispatcher[bank](stagingFile);
